/*iINSERTS DE TESTE*/
INSERT INTO USUARIO VALUES(NULL,'GU3079589','ALLAN',NULL,'11941328006');
INSERT INTO USUARIO VALUES(NULL,'GU3043213','JOAO',NULL,'11941128006');
INSERT INTO USUARIO VALUES(NULL,'GU3079581','CINTIA',NULL,'11951328006');


/*INSERTS ESTÁTICOS (DEFINITIVOS)*/
INSERT INTO CATEGORIA VALUES(NULL,'VESTUÁRIO','PEÇAS DE ROUPA COMO: CAMISETAS, BONÉS, SAPATOS, ETC...');
INSERT INTO CATEGORIA VALUES(NULL,'ELETRÔNICO','ELETRÔNICOS COMO: CELULARES, NOTEBOOKS, FONES, ETC...');
INSERT INTO CATEGORIA VALUES(NULL,'ITEM PESSOAL','ITENS COMO: GARRAFAS, ESCOVAS DE DENTE, MAQUIAGENS, ETC...');

/*INSERTS ESTÁTICOS (DEFINITIVOS)*/
INSERT INTO LOCAL VALUES(NULL,'REFEITÓRIO','REFEITÓRIO EXTERNO, PRÓXIMO À SAÍDA');
INSERT INTO LOCAL VALUES(NULL,'BIBLIOTECA','BIBLIOTECA EXTERNA, PRÓXIMO AO REFEITÓRIO');
INSERT INTO LOCAL VALUES(NULL,'QUADRA','QUADRA EXTERNA, PRÓXIMO AO PRÉDIO G');
INSERT INTO LOCAL VALUES(NULL,'SALA DE AULA PRÉDIO F','SALAS DE AULA QUE COMPÕEM O PRÉDIO F');
INSERT INTO LOCAL VALUES(NULL,'SALA DE AULA PRÉDIO G','SALAS DE AULA QUE COMPÕEM O PRÉDIO G');
INSERT INTO LOCAL VALUES(NULL,'PLAYGROUND','PLAYGROUND EXTERNO, ONDE FICAM AS MESAS DE PING PONG');
INSERT INTO LOCAL VALUES(NULL,'BANHEIRO','BANHEIRO DO PRÉDIO');

/*INSERTS DE TESTE*/
INSERT INTO OBJETO VALUES(NULL,'CAMISETA PRETA','CAMISETA PRETA COM UM RASGO NA PARTE DAS AXILAS','2026-10-4',1);
INSERT INTO OBJETO VALUES(NULL,'FONE DE OUVIDO','FONE DE OUVIDO COM FIO BRANCO','2026-10-04',2);
INSERT INTO OBJETO VALUES(NULL,'GARRAFA','GARRAFA STANLEY ROXA ESCURA','2026-10-04',3);


/*INSERTS DE TESTE*/
INSERT INTO OCORRENCIA VALUES (NULL,'ENCONTRADO','2026-10-04','ENCONTREI ESSA CAMISETA NA QUADRA DA ESCOLA','ATIVO',1,1,3);
INSERT INTO OCORRENCIA VALUES (NULL,'ENCONTRADO','2026-10-04','ENCONTREI ESSE FONE EM CIMA DA MESA NA SALA F1','RESOLVIDO',3,2,4);
INSERT INTO OCORRENCIA VALUES (NULL,'ENCONTRADO','2026-10-04','ENCONTREI ESSA GARRAFA EM CIMA DO BANCO, NO PLAYGROUND','ATIVO',1,3,6);