/*SELECT - TODOS OS DADOS AGRUPADOS*/
CREATE VIEW VW_TODOS_OS_DADOS AS
SELECT U.MATRICULA, U.NOME_USUARIO, O.NOME_OBJETO, L.NOME_LOCAL, OC.STATUS, OC.DATA_OCORRENCIA, U.TELEFONE
FROM OCORRENCIA OC
INNER JOIN USUARIO U
ON U.IDUSUARIO = OC.ID_USUARIO 
INNER JOIN LOCAL L 
ON L.IDLOCAL = OC.ID_LOCAL 
INNER JOIN OBJETO O 
ON O.IDOBJETO = OC.ID_OBJETO ;

SELECT * FROM VW_TODOS_OS_DADOS;

/*SELECT - SOMENTE OBJETOS ATIVOS*/
CREATE VIEW VW_DADOS_ATIVOS AS
SELECT U.MATRICULA, U.NOME_USUARIO, O.NOME_OBJETO, L.NOME_LOCAL, OC.STATUS, OC.DATA_OCORRENCIA, U.TELEFONE
FROM OCORRENCIA OC
INNER JOIN USUARIO U
ON U.IDUSUARIO = OC.ID_USUARIO 
INNER JOIN LOCAL L 
ON L.IDLOCAL = OC.ID_LOCAL 
INNER JOIN OBJETO O 
ON O.IDOBJETO = OC.ID_OBJETO
WHERE OC.STATUS = 'ATIVO' ;

SELECT * FROM VW_DADOS_ATIVOS;

/*SELECT - SOMENTE OBJETOS RESOLVIDOS*/
CREATE VIEW VW_DADOS_RESOLVIDOS AS
SELECT U.MATRICULA, U.NOME_USUARIO, O.NOME_OBJETO, L.NOME_LOCAL, OC.STATUS, OC.DATA_OCORRENCIA, U.TELEFONE
FROM OCORRENCIA OC
INNER JOIN USUARIO U
ON U.IDUSUARIO = OC.ID_USUARIO 
INNER JOIN LOCAL L 
ON L.IDLOCAL = OC.ID_LOCAL 
INNER JOIN OBJETO O 
ON O.IDOBJETO = OC.ID_OBJETO
WHERE OC.STATUS = 'RESOLVIDO' ;

SELECT * FROM VW_DADOS_RESOLVIDOS;

/*SELECT - QUANTIDADE DE OCORRENCIAS DE TODOS OS LOCAIS*/
CREATE VIEW VW_QTD_LOCAIS AS
SELECT 
    L.NOME_LOCAL,
    COUNT(*) AS OCORRENCIAS
FROM LOCAL L
INNER JOIN OCORRENCIA OC
    ON L.IDLOCAL = OC.ID_LOCAL
GROUP BY L.IDLOCAL, L.NOME_LOCAL;

SELECT * FROM VW_QTD_LOCAIS;

/*SELECT - QUANTIDADE DE OCORRENCIAS DE UM DETERMINADO LOCAL*/
DELIMITER $
CREATE PROCEDURE VER_QTD_LOCAL(ID INT)
BEGIN
	SELECT 
	    L.NOME_LOCAL,
	    COUNT(*) AS OCORRENCIAS
	FROM LOCAL L
	INNER JOIN OCORRENCIA OC
	    ON L.IDLOCAL = OC.ID_LOCAL
	WHERE L.IDLOCAL = ID
	GROUP BY L.IDLOCAL, L.NOME_LOCAL;
END $
DELIMITER ;

CALL VER_QTD_LOCAL(x);

/*SELECT - QUANTIDADE DE OCORRENCIAS DE UMA PESSOA*/
DELIMITER $
CREATE PROCEDURE VER_QTD_PESSOA(ID INT)
BEGIN
	SELECT 
	    U.NOME_USUARIO,
	    COUNT(*) AS OCORRENCIAS
	FROM USUARIO U 
	INNER JOIN OCORRENCIA OC
	    ON U.IDUSUARIO = OC.ID_USUARIO
	WHERE U.IDUSUARIO = ID
	GROUP BY U.IDUSUARIO, U.NOME_USUARIO;
END $
DELIMITER ;

CALL VER_QTD_PESSOA(x);