DROP DATABASE IF EXISTS ACHADOS_E_PERDIDOS;

CREATE DATABASE ACHADOS_E_PERDIDOS; 

USE ACHADOS_E_PERDIDOS; 


CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	MATRICULA VARCHAR(9) NOT NULL UNIQUE,
	NOME_USUARIO VARCHAR(100) NOT NULL,
	FOTO VARCHAR(255),
	TELEFONE VARCHAR(12) UNIQUE
);

CREATE TABLE CATEGORIA(
	IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
	NOME_CATEGORIA VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(300)
);

CREATE TABLE LOCAL(
	IDLOCAL INT PRIMARY KEY AUTO_INCREMENT,
	NOME_LOCAL VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(300)
);

CREATE TABLE OBJETO(
	IDOBJETO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_OBJETO VARCHAR(30) NOT NULL,
	DESCRICAO VARCHAR(300),
	DATA_CADASTRO DATETIME,
	ID_CATEGORIA INT NOT NULL
);

ALTER TABLE OBJETO ADD CONSTRAINT FK_OBJETO_CATEGORIA
FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA);

CREATE TABLE OCORRENCIA(
	IDOCORRENCIA INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('PERDIDO', 'ENCONTRADO') NOT NULL,
	DATA_OCORRENCIA DATETIME NOT NULL,
	DESCRICAO VARCHAR(300),
	STATUS ENUM ('ATIVO','RESOLVIDO','CANCELADO') NOT NULL,
	ID_USUARIO INT NOT NULL,
	ID_OBJETO INT NOT NULL,
	ID_LOCAL INT NOT NULL
);

ALTER TABLE OCORRENCIA ADD CONSTRAINT FK_OCORRENCIA_USUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(IDUSUARIO);

ALTER TABLE OCORRENCIA ADD CONSTRAINT FK_OCORRENCIA_OBJETO
FOREIGN KEY (ID_OBJETO) REFERENCES OBJETO(IDOBJETO);

ALTER TABLE OCORRENCIA ADD CONSTRAINT FK_OCORRENCIA_LOCAL
FOREIGN KEY (ID_LOCAL) REFERENCES LOCAL(IDLOCAL);


/*TRIGGER PARA IMPEDIR DATA FUTURA*/
DELIMITER $

CREATE TRIGGER TR_VERIFICA_DATA_OCORRENCIA
BEFORE INSERT ON OCORRENCIA
FOR EACH ROW
BEGIN
    IF NEW.DATA_OCORRENCIA > NOW() THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'A data da ocorrência não pode ser futura.';
    END IF;
END $

DELIMITER ;